BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Roles" (
	"IdRol"	INTEGER NOT NULL,
	"Rol"	TEXT NOT NULL,
	"EsActivo"	INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY("IdRol" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Usuarios" (
	"IdUsuario"	INTEGER NOT NULL,
	"NombreUsuario"	TEXT NOT NULL UNIQUE,
	"Nombre"	TEXT NOT NULL,
	"Apellido"	TEXT NOT NULL,
	"IdRol"	INTEGER NOT NULL,
	PRIMARY KEY("IdUsuario" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Clientes" (
	"IdCliente"	INTEGER NOT NULL,
	"NombreUsuario"	TEXT NOT NULL UNIQUE,
	"Nombre"	TEXT NOT NULL,
	"Apellido"	TEXT NOT NULL,
	"Vip"	INTEGER NOT NULL,
	"EsActivo"	INTEGER NOT NULL DEFAULT 1,
	"Email"	TEXT,
	PRIMARY KEY("IdCliente" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Descuentos" (
	"IdDescuento"	INTEGER NOT NULL,
	"TipoSala"	TEXT NOT NULL,
	"Dia"	TEXT NOT NULL,
	"Descuento"	REAL NOT NULL,
	PRIMARY KEY("IdDescuento" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Peliculas" (
	"IdPelicula"	INTEGER NOT NULL,
	"NombrePelicula"	TEXT NOT NULL,
	"Genero"	TEXT NOT NULL,
	"Idioma"	TEXT NOT NULL,
	PRIMARY KEY("IdPelicula" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Reservas" (
	"IdCliente"	INTEGER NOT NULL,
	"IdSala"	INTEGER NOT NULL,
	"IdReserva"	INTEGER NOT NULL,
	"IdPelicula"	INTEGER NOT NULL,
	"Precio"	REAL NOT NULL,
	PRIMARY KEY("IdReserva" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Salas" (
	"IdSala"	INTEGER NOT NULL,
	"NombreSala"	TEXT NOT NULL UNIQUE,
	"Tipo"	TEXT NOT NULL,
	"Capacidad"	INTEGER NOT NULL,
	"Precio"	REAL NOT NULL,
	"IdDescuento"	INTEGER NOT NULL,
	PRIMARY KEY("IdSala" AUTOINCREMENT)
);
COMMIT;
